#!/bin/bash

set -e

# 判断是否是linux 系统
if [[ `uname` != "Linux" ]] ; then
  echo [Error]: System is not Linux !
  exit 1
fi

# 判断Linux发行版
if [ ! -r "/etc/os-release" ] ; then
  echo '[Error]: File `os-release` unexist!'
  exit 1
fi

# 检测当前用户是否有root权限
if [ ! "$(id -u)" -eq 0 ]; then
  echo "[Error]: Must be root user!"
  exit 1
fi

. /etc/os-release
DISTRO=$ID

echo Your Linux distro: $DISTRO

case $DISTRO in
arch)
  # 1. 更换镜像源
  echo Change pacman source...
  echo
  cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
  echo -e "# Generated by init.sh\n
Server = http://mirrors.aliyun.com/archlinux/\$repo/os/\$arch
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/\$repo/os/\$arch
Server = http://mirrors.ustc.edu.cn/archlinux/\$repo/os/\$arch
Server = https://mirrors.neusoft.edu.cn/archlinux/\$repo/os/\$arch
" > /etc/pacman.d/mirrorlist

  # 2. 更新系统
  echo "update system..."
  echo
  pacman -Syyu --noconfirm
  # 3. 安装必要软件
  echo install packages...
  pacman -S --noconfirm --need neovim fish yazi btop tmux git chezmoi wget curl
  ;;
debian)
  # 更换镜像源
  echo Change Apt source to tsinghua...
  cp /etc/apt/sources.list /etc/apt/sources.list.bak
  echo "# Generated by init.sh\n
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free non-free-firmware
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free non-free-firmware
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main contrib non-free non-free-firmware

#deb https://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
deb https://mirrors.tuna.tsinghua.edu.cn/debian-security bookworm-security main contrib non-free non-free-firmware
" > /etc/apt/sources.list
  # 更新系统
  apt update
  apt upgrade -y
  apt install -y git fish tmux ranger btop neovim wget
  ;;
opensuse-tumbleweed)
  # 更换镜像源
  zypper mr -da
  zypper ar -cfg 'http://mirrors.tuna.tsinghua.edu.cn/opensuse/tumbleweed/repo/oss/' tuna-oss
  zypper ar -cfg 'http://mirrors.tuna.tsinghua.edu.cn/opensuse/tumbleweed/repo/non-oss/' tuna-non-oss
  zypper ref
  zypper in -y --no-recommends fish yazi neovim tmux git btop chezmoi wget curl
  # 关闭zypper安装推介
  cp /etc/zypp/zypper.conf /etc/zypp/zypper.conf.bak
  sed -i 's/# installRecommends = yes/installRecommends = no/' /etc/zypp/zypper.conf
  ;;
*)
  echo Unsupport Linux Distro!
  exit 1
  ;;
esac

echo change packageStorage complete!
echo
echo configrate root...
echo

bash <(curl -fsSL https://ghfast.top/https://raw.githubusercontent.com/ListenV/ServerInit/main/init-server.sh)